// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvmbpsbzmfxszuktmeek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2bWJwc2J6bWZ4c3p1a3RtZWVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM0MDI1ODIsImV4cCI6MjA3ODk3ODU4Mn0.rSHIyOqac8Rwc0WamdayboHjtO352xassKZ4T7gJWrc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});